### ISSUE TITLE
您好，可以请问下这个数据集吗

### ISSUE THREAD

**Issue by lili1147** [mkrupczak3/DeepCredit#1]

**Comment by mkrupczak3** [comment]
Sure

It's not really my data though

You should ask the authors of this research paper

I've uploaded the document to GitHub

The author's names are at the top of the document.

当然

虽然这不是我的数据

你应该问这篇研究论文的作者

我已将文档上传到GitHub

作者的姓名在文档的顶部。

**Comment by lili1147** [comment]
Thank you
